blank_issues_enabled: true
contact_links:
  - name: Telegram
    url: https://telegram.me/prodigy_infotech
    about: Join our Telegram group for Disucussion
  - name: Website
    url: https://prodigyinfotech.dev/
    about: Visit to know more
