name: 🚀 Project
description: "Submit a proposal for a new project"
title: "🚀 Project: "
labels: [project]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our new Project request form 🙏
  - type: textarea
    id: project-description
    validations:
      required: true
    attributes:
      label: "🔖 Project description"
      description: "A clear and concise description of what the project is."
      placeholder: "The project is about ..."
  - type: textarea
    id: pitch
    validations:
      required: true
    attributes:
      label: "🎤 Pitch"
      description: "Please explain why this project should be added and how it is implemented."
      placeholder: "This project has ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar project request?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)"
          required: true
